apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wellington-garcia-com-tls
spec:
  secretName: wellington-garcia-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wellington-garcia.com
  dnsNames:
    - wellingtongarcia.com
    - www.wellingtongarcia.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - wellingtongarcia.com
          - www.wellingtongarcia.com
